Convert Sphinx conf.py to Python 3.x syntax
Fixes sphinx.errors.SphinxWarning raised when running tox -e docs-html

SyntaxError: Missing parentheses in call to 'print'. Did you mean
print('To build the documentation, The distribution information of
Jinja2')?
...
sphinx.errors.SphinxWarning: Support for evaluating Python 2 syntax is
deprecated and will be removed in Sphinx 4.0. Convert
/home/alex/src/jinja2/docs/conf.py to Python 3 syntax.